# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-29 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_delete_comment'),
        ('comme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentario',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
        ),
    ]
