# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-28 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20160722_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commfield', models.TextField()),
                ('publishdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
