# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-28 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_commentario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commentario',
            new_name='Comment',
        ),
    ]
