# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-28 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commfield', models.TextField()),
                ('pubdate', models.DateTimeField()),
            ],
        ),
    ]
