# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-28 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20160728_1528'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
