# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-04 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_commentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentario',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.Post'),
        ),
    ]
