# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-13 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20160804_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev', models.CharField(max_length=120)),
            ],
        ),
    ]
