# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-13 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_prev'),
    ]

    operations = [
        migrations.AddField(
            model_name='prev',
            name='heh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preview', to='posts.Post'),
        ),
    ]
