# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-15 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_prev_heh'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentario',
            name='name',
            field=models.CharField(default='Your name', max_length=20),
        ),
    ]
