# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-15 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_commentario_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='prev',
            field=models.CharField(default='Preview', max_length=120),
        ),
        migrations.AlterField(
            model_name='commentario',
            name='name',
            field=models.CharField(default='Enter your name...', max_length=20),
        ),
    ]
